### ISSUE TITLE
US01  -  Menu

### ISSUE THREAD

**Issue by gabrielademoraes** [2018-2-Desenho/CabecaVoleiJoelhoPe#25]
Eu, como jogador, desejo visualizar e escolher as opções do jogo por meio de um menu que será a tela inicial.

**Tasks**:
- [ ]  Deve possuir um botão de “Jogar”;
- [ ]  Deve possuir um botão de “Recuperar Progresso”;
- [ ]  Deve possuir um botão de “Configurações”;
- [ ]  Deve possuir um botão de “Ajuda”;
- [ ]  Deve possuir um botão de “Créditos”;
- [ ]  Deve possuir um botão de “Sair”;
- [ ]  Na parte superior deve ter o título do jogo;
- [ ]  Na parte inferior  deve ter breves instruções de como controlar o menu;
- [ ]  Deve ser controlado por meio do teclado;
- [ ]  Deve ser construído de maneira que seja intuitivo para o usuário;
