### ISSUE TITLE
TS01 - Aplicar a parte de arte no jogo

### ISSUE THREAD

**Issue by gabrielademoraes** [2018-2-Desenho/CabecaVoleiJoelhoPe#26]
Eu, como desenvolvedor,  desejo adicionar a arte do jogo.

**Tasks**:
- [x] Fazer skins para os personagens;
- [x] Adicionar plano de fundo das arenas;
- [x] Adicionar skin na bola;
- [x] Adicionar skin na rede.
