### ISSUE TITLE
TS02 - Criar estrutura de sprites

### ISSUE THREAD

**Issue by gabrielademoraes** [2018-2-Desenho/CabecaVoleiJoelhoPe#27]
Eu, como desenvolvedor, desejo definir a estrutura geral para os objetos que aparecerão na tela.

**Tasks**:
- [ ] Definir a entidade abstrata geral;
- [ ] Definir a entidade abstrata dinâmica;
- [ ] Definir a entidade estática.
