### ISSUE TITLE
TS03 - Criar estrutura de gerentes do jogo

### ISSUE THREAD

**Issue by gabrielademoraes** [2018-2-Desenho/CabecaVoleiJoelhoPe#28]
Eu, como desenvolvedor, desejo definir a estrutura geral para os managers do jogo.

**Tasks**:
- [x] Definir o audio manager;
- [x] Definir o spriteAnimation manager;
- [x] Definir a image manager;
- [x] Definir a font manager.
- [x] Definir o input manager;
