### ISSUE TITLE
US13 - Definir classe personagem

### ISSUE THREAD

**Issue by gabrielademoraes** [2018-2-Desenho/CabecaVoleiJoelhoPe#30]
Eu, como usuário, desejo conseguir movimentar meu personagem pela tela .

**Tasks**:
- [ ] Adicionar personagem com formato geométrico;
- [ ] O personagem deve se movimentar no eixo X;
- [ ] O personagem deve se movimentar no eixo Y.
