### ISSUE TITLE
US02  -  Selecionar Personagem

### ISSUE THREAD

**Issue by gabrielademoraes** [2018-2-Desenho/CabecaVoleiJoelhoPe#33]
Eu, como jogador, desejo selecionar um personagem para jogar.

**Tasks**:
- [ ] Deve possuir 8 personagens selecionáveis;
- [ ]  Na parte superior deve ter a instrução “Selecione o personagem” ou algo similar;
- [ ]  Deve possuir um botão de “Anterior” para voltar à escolha do modo de jogo;
- [ ]  Deve possuir um botão de “Próximo” para avançar à escolha da arena  ;
- [ ]  Deve ser controlado por meio do teclado;
- [ ]  Na parte inferior  deve ter breves instruções de como controlar o menu;
- [ ]  Deve ser construído de maneira que seja intuitivo para o usuário;
