### ISSUE TITLE
US03  -   Selecionar Arena

### ISSUE THREAD

**Issue by gabrielademoraes** [2018-2-Desenho/CabecaVoleiJoelhoPe#34]
Eu, como jogador, desejo selecionar uma arena para realizar a partida

**Tasks**:
- [ ] Deve possuir 8 arenas selecionáveis;
- [ ]  Na parte superior deve ter a instrução “Selecione a arena” ou algo similar;
- [ ]  Deve possuir um botão de “Anterior” para voltar à escolha do personagem;
- [ ]  Deve possuir um botão de “Próximo” para avançar à partida  ;
- [ ]  Deve ser controlado por meio do teclado;
- [ ]  Na parte inferior  deve ter breves instruções de como controlar o menu;
- [ ]  Deve ser construído de maneira que seja intuitivo para o usuário;
