### ISSUE TITLE
US04 -  Selecionar a opção “Configurações” no Menu

### ISSUE THREAD

**Issue by gabrielademoraes** [2018-2-Desenho/CabecaVoleiJoelhoPe#35]
Eu, como jogador, desejo alterar as configurações do jogo.

**Tasks**:
- [ ] Na parte superior deve ter o título “Configurações” ou algo similar;
- [ ] Deve permitir que o usuário ajuste o volume do jogo;
- [ ] Deve possuir um botão “Anterior” para retornar ao menu principal;
