### ISSUE TITLE
US05 -  Selecionar a opção “Ajuda” no Menu

### ISSUE THREAD

**Issue by gabrielademoraes** [2018-2-Desenho/CabecaVoleiJoelhoPe#36]
Eu, como jogador,  desejo visualizar os comandos e regras do jogo.

**Tasks**:
- [ ] Na parte superior deve ter o título “Ajuda” ou algo similar;
- [ ] Deve apresentar as regras do jogo e os controles;
- [ ] Deve possuir um botão “Anterior” para retornar ao menu principal
