### ISSUE TITLE
US06 -  Selecionar a opção “Créditos” no Menu

### ISSUE THREAD

**Issue by gabrielademoraes** [2018-2-Desenho/CabecaVoleiJoelhoPe#37]
Eu, como jogador,  desejo visualizar quem são os desenvolvedores e os créditos de imagens e sons.

**Tasks**:
- [ ] Na parte superior deve ter o título “Créditos” ou algo similar;
- [ ] Deve apresentar o nome dos desenvolvedores, bem como os créditos para as imagens e sons;
- [ ] Deve possuir um botão “Anterior” para retornar ao menu principal
