### ISSUE TITLE
US08-  Definir classes Character/ Player

### ISSUE THREAD

**Issue by gabrielademoraes** [2018-2-Desenho/CabecaVoleiJoelhoPe#39]
Eu, como usuário, desejo conseguir movimentar meu personagem pela tela .

**Tasks**:
- [ ] Adicionar personagem com formato geométrico;
- [ ] O personagem deve se movimentar no eixo X;
- [ ] O personagem deve se movimentar no eixo Y.

**Comment by lukassxp** [comment]
Foi decidido pelo grupo implementar diretamente a classe Player. Implementada em #48.
